name: "Branch Naming Convention Check"

on:
  push:
    branches-ignore: 
      - 'main'
      - 'develop'
  pull_request:
    branches-ignore: 
      - 'main'
      - 'develop'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | grep -E "^(feature|bug|chore)/[a-zA-Z0-9_-]+$")
          if [[ ! $BRANCH_NAME ]]; then
            echo "Invalid branch name! Branch names in this repo must adhere to the pattern: '(feature|bug|chore)/<name>'."
            exit 1
          fi
